### ISSUE TITLE
Incorrect HWID used 

### ISSUE THREAD

**Issue by wfhm** [Telerik-Verified-Plugins/Pushwoosh#8]
Hey guys,

I'm contacting you on behalf of one of our clients here at Pushwoosh. The 6.0.0 version of this fork is using an outdated version of our iOS SDK which does not set a correct device HWID on iOS 10 devices when communicating with Pushwoosh backend, resulting in these requests failing. 

The fix was rolled out with [6.5.0](https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/tree/6.5.0) release, and the latest version is 7.0.4.

This issue completely breaks plugin's functionality, so we kindly ask you to update it.

Regards,
Pushwoosh Team

**Comment by EddyVerbruggen** [comment]
Thanks for letting us know, @wfhm - our fork has been updated.
